# Generated by Django 5.0.2 on 2024-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_blogpost_content_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_sign',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
    ]
