# Generated by Django 5.0.2 on 2024-02-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_contact_email_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/', verbose_name='image'),
        ),
    ]
