# Generated by Django 5.0.2 on 2024-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='image'),
        ),
    ]
