# Generated by Django 5.0.2 on 2024-04-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_image_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.CharField()),
                ('content', models.TextField(max_length=500, verbose_name='content')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='preview')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('publication_sign', models.BooleanField(default=False, verbose_name='public')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, verbose_name='description'),
        ),
    ]
