# Generated by Django 5.0.2 on 2024-04-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_blogpost_alter_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
