# Generated by Django 5.0.2 on 2024-04-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_version_sign_version_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
