# Generated by Django 4.2 on 2024-06-07 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_cancel_publication', 'Can cancel publication'), ('can_change_description', 'Can change description')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'permissions': [('can_cancel_publication', 'Can cancel publication')], 'verbose_name': 'Version', 'verbose_name_plural': 'Versions'},
        ),
        migrations.AddField(
            model_name='version',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
