# Generated by Django 4.2 on 2024-06-07 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
